"""empty message

Revision ID: 0ab352f9eb15
Revises: f2591591fddf
Create Date: 2017-01-25 11:54:45.925281

"""

# revision identifiers, used by Alembic.
revision = '0ab352f9eb15'
down_revision = 'f2591591fddf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_sub_sub_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('product_category_id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('product_sub_type_id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['product_sub_type_id'], ['product_sub_types.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_sub_sub_types')
    ### end Alembic commands ###
