"""empty message

Revision ID: 1fb898d1d4a9
Revises: b2ca146c26bd
Create Date: 2016-10-25 20:46:33.920681

"""

# revision identifiers, used by Alembic.
revision = '1fb898d1d4a9'
down_revision = 'b2ca146c26bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'products', 'vehicle_Type', ['product_type_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    ### end Alembic commands ###
