"""empty message

Revision ID: 25ca21c14628
Revises: e127bbe5e227
Create Date: 2016-10-25 12:08:30.080957

"""

# revision identifiers, used by Alembic.
revision = '25ca21c14628'
down_revision = 'e127bbe5e227'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('items')
    op.drop_table('itemtypes')
    op.drop_column('product_types', 'product')
    op.drop_column('product_types', 'description')
    op.drop_column('product_types', 'review')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_types', sa.Column('review', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('product_types', sa.Column('description', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('product_types', sa.Column('product', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('itemtypes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u"nextval('itemtypes_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('descr', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'itemtypes_pkey'),
    sa.UniqueConstraint('descr', name=u'itemtypes_descr_key'),
    sa.UniqueConstraint('name', name=u'itemtypes_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['type_id'], [u'itemtypes.id'], name=u'items_type_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'items_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'items_pkey'),
    sa.UniqueConstraint('name', name=u'items_name_key')
    )
    op.drop_table('product_reviews')
    op.drop_table('product_ratings')
    ### end Alembic commands ###
