"""empty message

Revision ID: 2c475d0b3f90
Revises: b4416c4f3922
Create Date: 2016-10-26 10:33:11.863123

"""

# revision identifiers, used by Alembic.
revision = '2c475d0b3f90'
down_revision = 'b4416c4f3922'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'category',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'category',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    ### end Alembic commands ###
