"""empty message

Revision ID: 316b78e292ea
Revises: 754302c3bc01
Create Date: 2016-12-06 14:58:43.212138

"""

# revision identifiers, used by Alembic.
revision = '316b78e292ea'
down_revision = '754302c3bc01'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('photo', sa.String(length=500), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'photo')
    ### end Alembic commands ###
