"""empty message

Revision ID: 53fcdfe2146d
Revises: None
Create Date: 2017-02-09 12:34:29.240409

"""

# revision identifiers, used by Alembic.
revision = '53fcdfe2146d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('lat', sa.Numeric(precision=15, scale=10), nullable=False))
    op.add_column('deliveries', sa.Column('lng', sa.Numeric(precision=15, scale=10), nullable=False))
    op.add_column('deliveries', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('deliveries', sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False))
    op.drop_column('deliveries', 'delivered')
    op.drop_column('deliveries', 'consumer')
    op.add_column('product_ratings', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('product_ratings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product_ratings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'product_ratings', 'products', ['product_id'], ['id'])
    op.drop_column('product_ratings', 'product')
    op.add_column('shopping_list', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('business_branch', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('business_name', sa.String(length=300), nullable=True))
    op.drop_constraint(u'users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.create_unique_constraint(u'users_username_key', 'users', ['username'])
    op.drop_column('users', 'business_name')
    op.drop_column('users', 'business_branch')
    op.drop_column('shopping_list', 'quantity')
    op.add_column('product_ratings', sa.Column('product', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_ratings', type_='foreignkey')
    op.drop_constraint(None, 'product_ratings', type_='foreignkey')
    op.drop_column('product_ratings', 'user_id')
    op.drop_column('product_ratings', 'product_id')
    op.add_column('deliveries', sa.Column('consumer', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('deliveries', sa.Column('delivered', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('deliveries', 'total')
    op.drop_column('deliveries', 'quantity')
    op.drop_column('deliveries', 'lng')
    op.drop_column('deliveries', 'lat')
    ### end Alembic commands ###
