"""empty message

Revision ID: 6143ecd5fac4
Revises: e898a0e6bfc3
Create Date: 2017-01-17 12:53:57.032063

"""

# revision identifiers, used by Alembic.
revision = '6143ecd5fac4'
down_revision = 'e898a0e6bfc3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo', sa.String(length=300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo')
    ### end Alembic commands ###
