"""empty message

Revision ID: 679763f2d873
Revises: None
Create Date: 2017-01-26 16:33:31.538676

"""

# revision identifiers, used by Alembic.
revision = '679763f2d873'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_sub_types', 'product_sub_type_id')
    op.create_foreign_key(None, 'products', 'product_sub_types', ['product_sub_type_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.add_column('product_sub_types', sa.Column('product_sub_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
