"""empty message

Revision ID: 6fbb62879307
Revises: 0d4ac9316efb
Create Date: 2016-12-06 11:10:28.560093

"""

# revision identifiers, used by Alembic.
revision = '6fbb62879307'
down_revision = '0d4ac9316efb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productname',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('photo', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productname')
    ### end Alembic commands ###
