"""empty message

Revision ID: 754302c3bc01
Revises: b4334700b9a1
Create Date: 2016-12-06 14:46:26.731935

"""

# revision identifiers, used by Alembic.
revision = '754302c3bc01'
down_revision = 'b4334700b9a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('packaging', sa.String(length=80), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'packaging')
    ### end Alembic commands ###
