"""empty message

Revision ID: 819d622f018e
Revises: None
Create Date: 2017-03-01 15:39:54.891638

"""

# revision identifiers, used by Alembic.
revision = '819d622f018e'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('photo', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('dob', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('home_address', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('work_address', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='customers_user_id_fkey'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='customers_vehicle_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='customers_pkey'),
    sa.UniqueConstraint('dob', name='customers_dob_key')
    )
    # ### end Alembic commands ###
