"""empty message

Revision ID: 869dbd4b33d2
Revises: c215039d7577
Create Date: 2017-01-16 09:45:42.604769

"""

# revision identifiers, used by Alembic.
revision = '869dbd4b33d2'
down_revision = 'c215039d7577'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transporter_current_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.String(length=80), nullable=True),
    sa.Column('longitude', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transporter_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('drivers_licence', sa.String(length=300), nullable=True),
    sa.Column('dl_expiry_date', sa.DateTime(), nullable=False),
    sa.Column('national_id', sa.String(length=300), nullable=False),
    sa.Column('good_conduct', sa.String(length=300), nullable=True),
    sa.Column('pin_certificate', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('drivers_licence')
    op.add_column(u'transporters', sa.Column('residence', sa.String(length=300), nullable=True))
    op.add_column(u'transporters', sa.Column('vehicle_color', sa.String(length=80), nullable=False))
    op.add_column(u'transporters', sa.Column('vehicle_reg_no', sa.String(length=80), nullable=False))
    op.add_column(u'transporters', sa.Column('vehicle_type', sa.String(length=80), nullable=False))
    op.drop_constraint(u'transporters_licence_key', 'transporters', type_='unique')
    op.create_unique_constraint(None, 'transporters', ['vehicle_color'])
    op.drop_constraint(u'transporters_vehicle_id_fkey', 'transporters', type_='foreignkey')
    op.drop_column(u'transporters', 'photo')
    op.drop_column(u'transporters', 'vehicle_id')
    op.drop_column(u'transporters', 'location')
    op.drop_column(u'transporters', 'licence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'transporters', sa.Column('licence', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column(u'transporters', sa.Column('location', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column(u'transporters', sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column(u'transporters', sa.Column('photo', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.create_foreign_key(u'transporters_vehicle_id_fkey', 'transporters', 'vehicles', ['vehicle_id'], ['id'])
    op.drop_constraint(None, 'transporters', type_='unique')
    op.create_unique_constraint(u'transporters_licence_key', 'transporters', ['licence'])
    op.drop_column(u'transporters', 'vehicle_type')
    op.drop_column(u'transporters', 'vehicle_reg_no')
    op.drop_column(u'transporters', 'vehicle_color')
    op.drop_column(u'transporters', 'residence')
    op.create_table('drivers_licence',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('transporter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('drivers_licence', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('dl_expiry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('national_id', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('good_conduct', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('pin_certificate', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('psv_drivers_licence', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('photo', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['transporter_id'], [u'transporters.id'], name=u'drivers_licence_transporter_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'drivers_licence_pkey')
    )
    op.drop_table('transporter_documents')
    op.drop_table('transporter_current_location')
    ### end Alembic commands ###
