"""empty message

Revision ID: 8b3b5dde009e
Revises: ec34cce59dcb
Create Date: 2016-10-25 18:43:09.529234

"""

# revision identifiers, used by Alembic.
revision = '8b3b5dde009e'
down_revision = 'ec34cce59dcb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('farmer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'users', ['farmer_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'farmer_id')
    ### end Alembic commands ###
