"""empty message

Revision ID: a52128e85a42
Revises: deac18fcff74
Create Date: 2017-02-07 15:41:29.393067

"""

# revision identifiers, used by Alembic.
revision = 'a52128e85a42'
down_revision = 'deac18fcff74'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('transporter', sa.Integer(), nullable=False),
    sa.Column('consumer', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('orders')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('delivered', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('consumer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transporter', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], [u'products.id'], name=u'orders_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'orders_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'orders_pkey')
    )
    op.drop_table('deliveries')
    ### end Alembic commands ###
