"""empty message

Revision ID: b2ca146c26bd
Revises: 8b3b5dde009e
Create Date: 2016-10-25 20:30:13.669690

"""

# revision identifiers, used by Alembic.
revision = 'b2ca146c26bd'
down_revision = '8b3b5dde009e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('colour', sa.String(length=30), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['vehicle_Type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('colour'),
    sa.UniqueConstraint('number')
    )
    op.drop_table('Vehicles')
    op.add_column('products', sa.Column('product_type_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'products_farmer_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'farmer_id')
    op.alter_column('vehicle_Type', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_constraint(u'vehicle_Type_name_key', 'vehicle_Type', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'vehicle_Type_name_key', 'vehicle_Type', ['name'])
    op.alter_column('vehicle_Type', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.add_column('products', sa.Column('farmer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'products_farmer_id_fkey', 'products', 'users', ['farmer_id'], ['id'])
    op.drop_column('products', 'product_type_id')
    op.create_table('Vehicles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Vehicles_id_seq"\'::regclass)'), nullable=False),
    sa.Column('number', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('colour', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('expiry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'Vehicles_pkey'),
    sa.UniqueConstraint('colour', name=u'Vehicles_colour_key'),
    sa.UniqueConstraint('number', name=u'Vehicles_number_key')
    )
    op.drop_table('vehicles')
    ### end Alembic commands ###
