"""empty message

Revision ID: b4334700b9a1
Revises: afc040437c04
Create Date: 2016-12-06 14:09:58.673382

"""

# revision identifiers, used by Alembic.
revision = 'b4334700b9a1'
down_revision = 'afc040437c04'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'photo')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('photo', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    ### end Alembic commands ###
