"""empty message

Revision ID: b4416c4f3922
Revises: 1fb898d1d4a9
Create Date: 2016-10-25 20:47:39.189846

"""

# revision identifiers, used by Alembic.
revision = 'b4416c4f3922'
down_revision = '1fb898d1d4a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('type_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'products_product_type_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'product_types', ['type_id'], ['id'])
    op.drop_column('products', 'product_type_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(u'products_product_type_id_fkey', 'products', 'vehicle_Type', ['product_type_id'], ['id'])
    op.drop_column('products', 'type_id')
    ### end Alembic commands ###
