"""empty message

Revision ID: c215039d7577
Revises: 35b393c01219
Create Date: 2017-01-12 16:14:09.240367

"""

# revision identifiers, used by Alembic.
revision = 'c215039d7577'
down_revision = '35b393c01219'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('primary_address', sa.String(length=300), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farmer_address')
    ### end Alembic commands ###
