"""empty message

Revision ID: c67c8b90fa31
Revises: a52128e85a42
Create Date: 2017-02-07 16:49:45.717919

"""

# revision identifiers, used by Alembic.
revision = 'c67c8b90fa31'
down_revision = 'a52128e85a42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'delivered')
    op.drop_column('deliveries', 'consumer')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('consumer', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('deliveries', sa.Column('delivered', sa.BOOLEAN(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
