"""empty message

Revision ID: deac18fcff74
Revises: None
Create Date: 2017-02-07 14:05:35.413772

"""

# revision identifiers, used by Alembic.
revision = 'deac18fcff74'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliveries')
    op.add_column('orders', sa.Column('consumer', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('transporter', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'transporter')
    op.drop_column('orders', 'consumer')
    op.create_table('deliveries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transporter', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('consumer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], [u'orders.id'], name=u'deliveries_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'deliveries_pkey')
    )
    ### end Alembic commands ###
