"""empty message

Revision ID: e127bbe5e227
Revises: d2957941d58e
Create Date: 2016-10-25 11:14:44.346092

"""

# revision identifiers, used by Alembic.
revision = 'e127bbe5e227'
down_revision = 'd2957941d58e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=15), nullable=False))
    op.alter_column('users', 'category',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'category',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('users', 'phone_number')
    ### end Alembic commands ###
