"""empty message

Revision ID: e4b0adafc7f5
Revises: 819d622f018e
Create Date: 2017-03-01 17:21:40.538214

"""

# revision identifiers, used by Alembic.
revision = 'e4b0adafc7f5'
down_revision = '819d622f018e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transporter_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transporter_ratings')
    # ### end Alembic commands ###
