"""empty message

Revision ID: e898a0e6bfc3
Revises: f398bf1b6b02
Create Date: 2017-01-16 16:09:46.229803

"""

# revision identifiers, used by Alembic.
revision = 'e898a0e6bfc3'
down_revision = 'f398bf1b6b02'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transporter_documents')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transporter_documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('drivers_licence', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('dl_expiry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('national_id', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('good_conduct', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('pin_certificate', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'transporter_documents_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'transporter_documents_pkey')
    )
    ### end Alembic commands ###
