"""empty message

Revision ID: ee8b76114f4a
Revises: None
Create Date: 2017-03-14 13:25:41.352267

"""

# revision identifiers, used by Alembic.
revision = 'ee8b76114f4a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('transporter', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Accepted', 'Delivered', 'Pending', name='order_status'), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('deliveries', 'lat')
    op.drop_column('deliveries', 'lng')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('lng', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=False))
    op.add_column('deliveries', sa.Column('lat', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=False))
    op.drop_table('orders')
    # ### end Alembic commands ###
