"""empty message

Revision ID: f2591591fddf
Revises: None
Create Date: 2017-01-25 11:10:33.247732

"""

# revision identifiers, used by Alembic.
revision = 'f2591591fddf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_sub_types', sa.Column('product_category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product_sub_types', 'product_categories', ['product_category_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_sub_types', type_='foreignkey')
    op.drop_column('product_sub_types', 'product_category_id')
    ### end Alembic commands ###
