"""empty message

Revision ID: f398bf1b6b02
Revises: 869dbd4b33d2
Create Date: 2017-01-16 11:29:55.476370

"""

# revision identifiers, used by Alembic.
revision = 'f398bf1b6b02'
down_revision = '869dbd4b33d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transporters', 'residence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transporters', sa.Column('residence', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    ### end Alembic commands ###
